feat: improved icons and footer
ReVanced/revanced-website pull request #141
Opened 2023-07-06 14:15 UTC by milksense

- Added arrow icon instead `+ or -` symbols
- Improved `font-weight` for `FooterSection` (mobile-friendly) ✌🏻 
<img src="https://github.com/revanced/revanced-website/assets/29128703/ade517f3-fcbf-4414-b80c-2d4979f1f26d" width="200">
<img src="https://github.com/revanced/revanced-website/assets/29128703/a2e096aa-ce73-4d6e-89bb-025156827677" width="200">

- Changed legacy `arrow` icon in `ContributorSection` dropdown
<img src="https://github.com/revanced/revanced-website/assets/29128703/b176f5f3-fc2e-4d60-a964-61543d51d85a" width="200">

2023-07-06 14:20 UTC, oSumAtrIX requested changes

2023-07-06 14:20 UTC, oSumAtrIX commented on src/layout/Footer/FooterHost.svelte
> +		<!-- Example: Add more items to wrap child elements -->
Why are these inside the PR? Please remove them

2023-07-10 00:31 UTC, milksense commented
@oSumAtrIX

2023-07-22 22:05 UTC, Ushie approved these changes

2023-07-22 22:05 UTC, merged