minify your svgs
ReVanced/revanced-website pull request #209
Opened 2023-12-29 21:17 UTC by KTibow

fingers crossed nothing broke

2023-12-30 11:24 UTC, oSumAtrIX commented
Please explain what this PR aims to do and what "mini dying svgs" means

2023-12-30 14:05 UTC, KTibow commented
> what this PR aims to do

Make images using the SVG format smaller by removing unnecessary material.

> and what "mini dying svgs" means

In the context of websites, "minify" refers to the process of making files smaller by removing unnecessary data without affecting their functionality or display. When applied to SVGs (Scalable Vector Graphics), minification involves removing unnecessary metadata, comments, empty tags, and other non-essential information that might have been included during the creation or editing process.

Minifying an SVG can improve the performance of a website by reducing the amount of data the client's browser has to download and process. This is particularly valuable for improving load times and reducing bandwidth usage. The visual quality of the SVG remains the same even after minification, as the process only strips out information that doesn’t affect the rendering of the image.

2023-12-30 22:20 UTC, Ushie requested changes
This breaks the wavey line in FooterHost

2023-12-31 20:18 UTC, Ushie approved these changes

2023-12-31 20:18 UTC, merged