fix: error page
revanced/revanced-website pull request #69
Opened 2023-02-09 10:01 UTC by zalnaRs

#60

2023-02-09 14:35 UTC, Axelen123 requested changes
Thank you for the pull request

2023-02-09 16:53 UTC, zalnaRs commented on svelte.config.js
> -			fallback: '404.html'
Ok I will add it back. I removed it because it didn't work in dev

2023-02-11 20:11 UTC, Axelen123 commented
It looks good now

2023-02-11 20:11 UTC, Axelen123 approved these changes

2023-02-11 20:12 UTC, merged

2023-02-11 20:16 UTC, xafn commented
thank